
package=com.pragma.crediya.solicitudes
systemProp.version=3.24.0
reactive=true
lombok=true
metrics=true
language=java
systemProp.sonar.gradle.skipCompile=true

org.gradle.jvmargs=-Xmx2g -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true

# La Configuration Cache puede romper tareas del plugin del scaffold.
# Habilítala solo si todo compila bien; si ves errores raros en validateStructure, ponla en false.
org.gradle.configuration-cache=false
# Si la usas:
# org.gradle.configuration-cache=true
# org.gradle.configuration-cache.parallel=true
# org.gradle.configuration-cache.integrity-check=true

org.gradle.logging.stacktrace=full
org.gradle.logging.level=info
