server:
  port: 8080
spring:
  application:
    name: crediya-solicitudes-ms
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/crediya
    username: postgres
    password: admin
  datasource:
    url: jdbc:postgresql://localhost:5432/crediya
    username: postgres
    password: admin
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    root: INFO
    com.pragma.crediya: INFO
